apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 192.168.233.133:32118/vbruno175:tagVersion
      ports:
        - containerPort: 8080
